var source =
	{
		matrix: [
		[
		{ number: 1, abbr: 'H', name: 'Hydrogen', latinName: 'Hydrogenium', atomicMass: 1.008, className: 'nonMetal' },
		{ number: 2, abbr: 'He', name: 'Helium', latinName: 'Helium', atomicMass: 4.003, className: 'nobleGas' }
		],
		[
		{ number: 3, abbr: 'Li', name: 'Lithium', latinName: 'Lithium', atomicMass: 6.941, className: 'alkaliMetal' },
		{ number: 4, abbr: 'Be', name: 'Beryllium', latinName: 'Beryllium', atomicMass: 9.012, className: 'alkaline' },
		{ number: 5, abbr: 'B', name: 'Boron', latinName: 'Borum', atomicMass: 10.811, className: 'semiMetal' },
		{ number: 6, abbr: 'C', name: 'Carbon', latinName: 'Carboneum', atomicMass: 12.011, className: 'nonMetal' },
		{ number: 7, abbr: 'N', name: 'Nitrogen', latinName: 'Nitrogenium', atomicMass: 14.007, className: 'nonMetal' },
		{ number: 8, abbr: 'O', name: 'Oxygen', latinName: 'Oxygenium', atomicMass: 15.999, className: 'nonMetal' },
		{ number: 9, abbr: 'F', name: 'Fluorine', latinName: 'Fluorum', atomicMass: 18.998, className: 'halogen' },
		{ number: 10, abbr: 'Ne', name: 'Neon', latinName: 'Neon', atomicMass: 20.180, className: 'nobleGas' }
		],
		[
		{ number: 11, abbr: 'Na', name: 'Sodium', latinName: 'Natrium', atomicMass: 22.990, className: 'alkaliMetal' },
		{ number: 12, abbr: 'Mg', name: 'Magnesium', latinName: 'Magnesium', atomicMass: 24.305, className: 'alkaline' },
		{ number: 13, abbr: 'Al', name: 'Aluminium', latinName: 'Aluminium', atomicMass: 26.982, className: 'basicMetal' },
		{ number: 14, abbr: 'Si', name: 'Silicon', latinName: 'Silicium', atomicMass: 28.086, className: 'semiMetal' },
		{ number: 15, abbr: 'P', name: 'Phosphorus', latinName: 'Phosphorus', atomicMass: 30.974, className: 'nonMetal' },
		{ number: 16, abbr: 'S', name: 'Sulfur', latinName: 'Sulfur', atomicMass: 32.066, className: 'nonMetal' },
		{ number: 17, abbr: 'Cl', name: 'Chlorine', latinName: 'Chlorum', atomicMass: 35.453, className: 'halogen' },
		{ number: 18, abbr: 'Ar', name: 'Argon', latinName: 'Argon', atomicMass: 39.948, className: 'nobleGas' }
		],
		[
		{ number: 19, abbr: 'K', name: 'Potassium', latinName: 'Kalium', atomicMass: 39.098, className: 'alkaliMetal' },
		{ number: 20, abbr: 'Ca', name: 'Calcium', latinName: 'Calcium', atomicMass: 40.078, className: 'alkaline' },
		{ number: 21, abbr: 'Sc', name: 'Scandium', latinName: 'Scandium', atomicMass: 44.956, className: 'transMetal' },
		{ number: 22, abbr: 'Ti', name: 'Titanium', latinName: 'Titanium', atomicMass: 47.88, className: 'transMetal' },
		{ number: 23, abbr: 'V', name: 'Vanadium', latinName: 'Vanadium', atomicMass: 50.942, className: 'transMetal' },
		{ number: 24, abbr: 'Cr', name: 'Chromium', latinName: 'Chromium', atomicMass: 51.996, className: 'transMetal' },
		{ number: 25, abbr: 'Mn', name: 'Manganese', latinName: 'Manganum', atomicMass: 54.938, className: 'transMetal' },
		{ number: 26, abbr: 'Fe', name: 'Iron', latinName: 'Ferrum', atomicMass: 55.933, className: 'transMetal' },
		{ number: 27, abbr: 'Co', name: 'Cobalt', latinName: 'Cobaltum', atomicMass: 58.933, className: 'transMetal' },
		{ number: 28, abbr: 'Ni', name: 'Nickel', latinName: 'Niccolum', atomicMass: 58.693, className: 'transMetal' },
		{ number: 29, abbr: 'Cu', name: 'Copper', latinName: 'Cuprum', atomicMass: 63.546, className: 'transMetal' },
		{ number: 30, abbr: 'Zn', name: 'Zinc', latinName: 'Zincum', atomicMass: 65.39, className: 'transMetal' },
		{ number: 31, abbr: 'Ga', name: 'Gallium', latinName: 'Gallium', atomicMass: 69.732, className: 'basicMetal' },
		{ number: 32, abbr: 'Ge', name: 'Germanium', latinName: 'Germanium', atomicMass: 72.61, className: 'semiMetal' },
		{ number: 33, abbr: 'As', name: 'Arsenic', latinName: 'Arsenicum', atomicMass: 74.922, className: 'semiMetal' },
		{ number: 34, abbr: 'Se', name: 'Selenium', latinName: 'Selenium', atomicMass: 78.972, className: 'nonMetal' },
		{ number: 35, abbr: 'Br', name: 'Bromine', latinName: 'Bromum', atomicMass: 79.904, className: 'halogen' },
		{ number: 36, abbr: 'Kr', name: 'Krypton', latinName: 'Krypton', atomicMass: 84.80, className: 'nobleGas' }
		],
		[
		{ number: 37, abbr: 'Rb', name: 'Rubidium', latinName: 'Rubidium', atomicMass: 84.468, className: 'alkaliMetal' },
		{ number: 38, abbr: 'Sr', name: 'Stronium', latinName: 'Stronium', atomicMass: 87.62, className: 'alkaline' },
		{ number: 39, abbr: 'Y', name: 'Yttrium', latinName: 'Yttrium', atomicMass: 88.906, className: 'transMetal' },
		{ number: 40, abbr: 'Zr', name: 'Zirconium', latinName: 'Zirconium', atomicMass: 91.224, className: 'transMetal' },
		{ number: 41, abbr: 'Nb', name: 'Niobium', latinName: 'Niobium', atomicMass: 92.906, className: 'transMetal' },
		{ number: 42, abbr: 'Mo', name: 'Molybdenum', latinName: 'Molybdenum', atomicMass: 95.95, className: 'transMetal' },
		{ number: 43, abbr: 'Tc', name: 'Technetium', latinName: 'Technetium', atomicMass: 98.907, className: 'transMetal' },
		{ number: 44, abbr: 'Ru', name: 'Ruthenium', latinName: 'Ruthenium', atomicMass: 101.07, className: 'transMetal' },
		{ number: 45, abbr: 'Rh', name: 'Rhodium', latinName: 'Rhodium', atomicMass: 102.906, className: 'transMetal' },
		{ number: 46, abbr: 'Pd', name: 'Palladium', latinName: 'Palladium', atomicMass: 106.42, className: 'transMetal' },
		{ number: 47, abbr: 'Ag', name: 'Silver', latinName: 'Argentum', atomicMass: 107.868, className: 'transMetal' },
		{ number: 48, abbr: 'Cd', name: 'Cadmium', latinName: 'Cadmium', atomicMass: 112.411, className: 'transMetal' },
		{ number: 49, abbr: 'In', name: 'Indium', latinName: 'Indium', atomicMass: 114.818, className: 'basicMetal' },
		{ number: 50, abbr: 'Sn', name: 'Tin', latinName: 'Stannum', atomicMass: 118.71, className: 'basicMetal' },
		{ number: 51, abbr: 'Sb', name: 'Antimony', latinName: 'Stibium', atomicMass: 121.760, className: 'semiMetal' },
		{ number: 52, abbr: 'Te', name: 'Tellurium', latinName: 'Tellurium', atomicMass: 127.6, className: 'semiMetal' },
		{ number: 53, abbr: 'I', name: 'Iodine', latinName: 'Iodum', atomicMass: 126.904, className: 'halogen' },
		{ number: 54, abbr: 'Xe', name: 'Xenon', latinName: 'Xenon', atomicMass: 131.29, className: 'nobleGas' },
		],
		[
		{ number: 55, abbr: 'Cs', name: 'Cesium', latinName: 'Cesium', atomicMass: 132.905, className: 'alkaliMetal' },
		{ number: 56, abbr: 'Ba', name: 'Barium', latinName: 'Barium', atomicMass: 137.327, className: 'alkaline' },
		{ number: '', abbr: '', name: '', latinName: '', atomicMass: '' },
		{ number: 72, abbr: 'Hf', name: 'Hafnium', latinName: 'Hafnium', atomicMass: 178.49, className: 'transMetal' },
		{ number: 73, abbr: 'Ta', name: 'Tantalum', latinName: 'Tantalum', atomicMass: 180.948, className: 'transMetal' },
		{ number: 74, abbr: 'W', name: 'Tungsten', latinName: 'Wolframium', atomicMass: 183.85, className: 'transMetal' },
		{ number: 75, abbr: 'Re', name: 'Rhenium', latinName: 'Rhenium', atomicMass: 186.207, className: 'transMetal' },
		{ number: 76, abbr: 'Os', name: 'Osmium', latinName: 'Osmium', atomicMass: 190.23, className: 'transMetal' },
		{ number: 77, abbr: 'Ir', name: 'Iridium', latinName: 'Iridium', atomicMass: 192.22, className: 'transMetal' },
		{ number: 78, abbr: 'Pt', name: 'Platinum', latinName: 'Platinum', atomicMass: 195.08, className: 'transMetal' },
		{ number: 79, abbr: 'Au', name: 'Gold', latinName: 'Aurum', atomicMass: 196.967, className: 'transMetal' },
		{ number: 80, abbr: 'Hg', name: 'Mercury', latinName: 'Hydragenium', atomicMass: 200.59, className: 'transMetal' },
		{ number: 81, abbr: 'Tl', name: 'Thallium', latinName: 'Thallium', atomicMass: 204.383, className: 'basicMetal' },
		{ number: 82, abbr: 'Pb', name: 'Lead', latinName: 'Plumbum', atomicMass: 207.2, className: 'basicMetal' },
		{ number: 83, abbr: 'Bi', name: 'Bismuth', latinName: 'Bismuthum', atomicMass: 208.980, className: 'basicMetal' },
		{ number: 84, abbr: 'Po', name: 'Polonium', latinName: 'Polonium', atomicMass: '[208.982]', className: 'semiMetal' },
		{ number: 85, abbr: 'At', name: 'Astatine', latinName: 'Astatium', atomicMass: 209.987, className: 'halogen' },
		{ number: 86, abbr: 'Rn', name: 'Radon', latinName: 'Radon', atomicMass: 222.018, className: 'nobleGas' },
		],
		[
		{ number: 87, abbr: 'Fr', name: 'Francium', latinName: '', atomicMass: 223.020, className: 'alkaliMetal' },
		{ number: 88, abbr: 'Ra', name: 'Radium', latinName: '', atomicMass: 226.025, className: 'alkaline' },
		{ number: '', abbr: '', name: '', latinName: '', atomicMass: '' },
		{ number: 104, abbr: 'Rf', name: 'Rutherfordium', latinName: '', atomicMass: '[261]', className: 'transMetal' },
		{ number: 105, abbr: 'Db', name: 'Dubnium', latinName: '', atomicMass: '[262]', className: 'transMetal' },
		{ number: 106, abbr: 'Sg', name: 'Seaborgium', latinName: '', atomicMass: '[266]', className: 'transMetal' },
		{ number: 107, abbr: 'Bh', name: 'Bohrium', latinName: '', atomicMass: '[264]', className: 'transMetal' },
		{ number: 108, abbr: 'Hs', name: 'Hassium', latinName: '', atomicMass: '[269]', className: 'transMetal' },
		{ number: 109, abbr: 'Mt', name: 'Meitnerium', latinName: '', atomicMass: '[268]', className: 'transMetal' },
		{ number: 110, abbr: 'Ds', name: 'Darmstadtium', latinName: '', atomicMass: '[269]', className: 'transMetal' },
		{ number: 111, abbr: 'Rg', name: 'Roentgenium', latinName: '', atomicMass: '[272]', className: 'transMetal' },
		{ number: 112, abbr: 'Cn', name: 'Copernicium', latinName: '', atomicMass: '[277]', className: 'transMetal' },
		{ number: 113, abbr: 'Uut', name: 'Ununtrium', latinName: '', atomicMass: 'unknown', className: 'basicMetal' },
		{ number: 114, abbr: 'Fl', name: 'Flerovium', latinName: '', atomicMass: '[289]', className: 'basicMetal' },
		{ number: 115, abbr: 'Uup', name: 'Ununpentium', latinName: '', atomicMass: 'unknown', className: 'basicMetal' },
		{ number: 116, abbr: 'Lv', name: 'Livermorium', latinName: '', atomicMass: '[298]', className: 'basicMetal' },
		{ number: 117, abbr: 'Uus', name: 'Ununseptium', latinName: '', atomicMass: 'unknown', className: 'halogen' },
		{ number: 118, abbr: 'Uuo', name: 'Ununoctium', latinName: '', atomicMass: 'unknown', className: 'nobleGas' },
		],
		[
		{ number: 57, abbr: 'La', name: 'Lanthanum', latinName: '', atomicMass: 138.906, className: 'lanthanide' },
		{ number: 58, abbr: 'Ce', name: 'Cerium', latinName: '', atomicMass: 140.115, className: 'lanthanide' },
		{ number: 59, abbr: 'Pr', name: 'Praseodymium', latinName: '', atomicMass: 140.908, className: 'lanthanide' },
		{ number: 60, abbr: 'Nd', name: 'Neodymium', latinName: '', atomicMass: 144.24, className: 'lanthanide' },
		{ number: 61, abbr: 'Pm', name: 'Promethium', latinName: '', atomicMass: 144.913, className: 'lanthanide' },
		{ number: 62, abbr: 'Sm', name: 'Samarium', latinName: '', atomicMass: 150.36, className: 'lanthanide' },
		{ number: 63, abbr: 'Eu', name: 'Europium', latinName: '', atomicMass: 151.966, className: 'lanthanide' },
		{ number: 64, abbr: 'Gd', name: 'Gadolinium', latinName: '', atomicMass: 157.25, className: 'lanthanide' },
		{ number: 65, abbr: 'Tb', name: 'Terbium', latinName: '', atomicMass: 158.925, className: 'lanthanide' },
		{ number: 66, abbr: 'Dy', name: 'Dysprosium', latinName: '', atomicMass: 162.50, className: 'lanthanide' },
		{ number: 67, abbr: 'Ho', name: 'Holmium', latinName: '', atomicMass: 164.930, className: 'lanthanide' },
		{ number: 68, abbr: 'Er', name: 'Erbium', latinName: '', atomicMass: 167.26, className: 'lanthanide' },
		{ number: 69, abbr: 'Tm', name: 'Thulium', latinName: '', atomicMass: 168.934, className: 'lanthanide' },
		{ number: 70, abbr: 'Yb', name: 'Ytterbium', latinName: '', atomicMass: 173.04, className: 'lanthanide' },
		{ number: 71, abbr: 'Lu', name: 'Lutetium', latinName: '', atomicMass: 174.967, className: 'lanthanide' },
		],
		[
		{ number: 89, abbr: 'Ac', name: 'Actinium', latinName: '', atomicMass: 227.028, className: 'actinide' },
		{ number: 90, abbr: 'Th', name: 'Thorium', latinName: '', atomicMass: 232.038, className: 'actinide' },
		{ number: 91, abbr: 'Pa', name: 'Protactinium', latinName: '', atomicMass: 231.036, className: 'actinide' },
		{ number: 92, abbr: 'U', name: 'Uranium', latinName: '', atomicMass: 238.029, className: 'actinide' },
		{ number: 93, abbr: 'Np', name: 'Neptunium', latinName: '', atomicMass: 237.048, className: 'actinide' },
		{ number: 94, abbr: 'Pu', name: 'Plutonium', latinName: '', atomicMass: 244.064, className: 'actinide' },
		{ number: 95, abbr: 'Am', name: 'Americium', latinName: '', atomicMass: 243.061, className: 'actinide' },
		{ number: 96, abbr: 'Cm', name: 'Curium', latinName: '', atomicMass: 247.070, className: 'actinide' },
		{ number: 97, abbr: 'Bk', name: 'Berkelium', latinName: '', atomicMass: 247.070, className: 'actinide' },
		{ number: 98, abbr: 'Cf', name: 'Californium', latinName: '', atomicMass: 251.080, className: 'actinide' },
		{ number: 99, abbr: 'Es', name: 'Einsteinium', latinName: '', atomicMass: '[254]', className: 'actinide' },
		{ number: 100, abbr: 'Fm', name: 'Fermium', latinName: '', atomicMass: 257.095, className: 'actinide' },
		{ number: 101, abbr: 'Md', name: 'Mendelevium', latinName: '', atomicMass: 258.1, className: 'actinide' },
		{ number: 102, abbr: 'No', name: 'Nobelium', latinName: '', atomicMass: 259.101, className: 'actinide' },
		{ number: 103, abbr: 'Lr', name: 'Lawrencium', latinName: '', atomicMass: '[262]', className: 'actinide' },

		]
		],
		slot: [
			{ elemType: 'Alkali Metal', className: 'alkaliMetal' },
			{ elemType: 'Alkaline Earth', className: 'alkaline' },
			{ elemType: 'Transition Metal', className: 'transMetal' },
			{ elemType: 'Basic Metal', className: 'basicMetal' },
			{ elemType: 'Semimetal', className: 'semiMetal' },
			{ elemType: 'Nonmetal', className: 'nonMetal' },
			{ elemType: 'Halogen', className: 'halogen' },
			{ elemType: 'Noble Gas', className: 'nobleGas' },
			{ elemType: 'Lanthanide', className: 'lanthanide' },
			{ elemType: 'Actinide', className: 'actinide' },
		]
	};